# -----------------------------------------------------------------------
#
#   Configuration Makefile for RH
#
#   Edit the variables below to reflect your compilers and environment.
#
# -----------------------------------------------------------------------

CC       = mpicc
CFLAGS   = -O2 -DHAVE_F90 -Wformat

F90C     = gfortran
F90FLAGS = -O2

LD       = mpicc
LDFLAGS  =

AR       = ar
ARFLAGS  = rs
RANLIB   = ranlib

HDF5_DIR = /Users/gskerr1/00_Packages/hdf5-1.12.1-install-parallel

# The OS variable should have the operative system name
# If the command below is unavailable, please edit manually
OS = $(shell uname -s)
