# -----------------------------------------------------------------------
#
#   Configuration Makefile for RH
#
#   Edit the variables below to reflect your compilers and environment.
#
# -----------------------------------------------------------------------

OPT = -O3 -march=core-avx2 

CC       = mpicc
CFLAGS   = ${OPT} -I/usr/include/tirpc/

F90C     = mpif90
F90FLAGS = ${OPT} 

LD       = mpif90
LDFLAGS  = -nofor-main -ltirpc

AR       = ar
ARFLAGS  = rs
RANLIB   = ranlib

#HDF5_DIR = /astro/local/hdf5/1.10.1/intel/

# The OS variable should have the operative system name
# If the command below is unavailable, please edit manually
OS = $(shell uname -s)
